'use strict';
const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {initializeApp}=require('firebase-admin/app');const {getFirestore,FieldValue}=require('firebase-admin/firestore');const {getAuth}=require('firebase-admin/auth');const P=require('./policy');
initializeApp();const db=getFirestore(),auth=getAuth();const collections=[...P.DATA,...P.ACCESS,'users'];const BOSS='2z3ikxeOWBZ8xccmjpTcVyfzfIX2';
async function readState(tx){const snapshots=await Promise.all(collections.map(k=>tx?tx.get(db.collection(k)):db.collection(k).get()));const s=Object.fromEntries(collections.map((k,i)=>[k,snapshots[i].docs.map(d=>({...d.data(),id:d.id}))]));const options=await (tx?tx.get(db.doc('settings/roleOptions')):db.doc('settings/roleOptions').get());s.roleOptions=options.data()||{};return s}
async function actor(req){if(!req.auth)throw new HttpsError('unauthenticated','请先登录');const [profile,account]=await Promise.all([db.doc('users/'+req.auth.uid).get(),auth.getUser(req.auth.uid)]);const u={...profile.data(),id:req.auth.uid};if(!profile.exists||u.inactive||account.disabled||Number(req.auth.token.auth_time||0)*1000<Date.parse(account.tokensValidAfterTime||'1970-01-01'))throw new HttpsError('permission-denied','账号未获授权或已停用');if(!P.ROLES.includes(u.role))throw new HttpsError('permission-denied','角色无效');await db.runTransaction(async tx=>{const ref=db.doc('limits/'+u.id),snap=await tx.get(ref),minute=Math.floor(Date.now()/60000),v=snap.data()||{};const count=v.minute===minute?v.count+1:1;if(count>120)throw new HttpsError('resource-exhausted','操作过于频繁，请稍后再试');tx.set(ref,{minute,count})});return u}
const stamp=(u,extra={})=>({time:new Date().toISOString(),user:u.name,userId:u.id,role:u.role,mode:'服务器审计',...extra});
async function load(u){const s=await db.runTransaction(tx=>readState(tx),{readOnly:true});const actual=s.users.find(x=>x.id===u.id);if(!actual||actual.inactive||actual.role!==u.role)throw new HttpsError('permission-denied','权限已变更，请重新登录');const visible=P.scope(s,u);const [logs,audits]=await Promise.all([u.role!=='团队'?db.collection('loginLogs').orderBy('time','desc').limit(200).get():null,P.ADMIN.includes(u.role)?db.collection('audit').orderBy('time','desc').limit(500).get():null]);return {db:Object.fromEntries(P.DATA.map(k=>[k,visible[k]])),access:{users:visible.users,assignments:visible.assignments,transferHistory:visible.transferHistory,roleOptions:visible.roleOptions,logs:logs?logs.docs.map(d=>({id:d.id,...d.data()})).reverse():[]},profile:{...u,email:u.email||''},audit:audits?audits.docs.map(d=>({id:d.id,...d.data()})).reverse():[]}}
async function mutate(u,patches){if(!Array.isArray(patches)||!patches.length||patches.length>150)throw new HttpsError('invalid-argument','单次最多修改150条记录，请分批导入');const disabled=[];await db.runTransaction(async tx=>{const s=await readState(tx);const current=s.users.find(x=>x.id===u.id);if(!current||current.inactive||current.role!==u.role)throw new HttpsError('permission-denied','权限已变更，请重新登录');const seen=new Set();for(const p of patches){P.authorizePatch(s,u,p);const key=p.collection+'/'+p.id;if(seen.has(key))throw Error('重复修改');seen.add(key);const actual=p.collection==='roleOptions'?s.roleOptions[p.id]||null:s[p.collection].find(x=>x.id===p.id)||null;if(!P.eq(actual,p.before??null))throw new HttpsError('aborted','资料已被其他同事更新，请刷新后再操作');if(p.after&&p.collection!=='roleOptions'&&p.after.id!==p.id)throw Error('编号不可更改');if(p.collection==='users'&&p.id===BOSS&&(p.after.role!=='老板'||p.after.inactive))throw Error('不能停用老板管理员');if(p.collection==='users'&&p.after.inactive)disabled.push(p.id);}
 for(const p of patches){if(p.collection==='roleOptions'){s.roleOptions[p.id]=p.after;continue}const index=s[p.collection].findIndex(r=>r.id===p.id);if(index>=0)s[p.collection].splice(index,1);if(p.after)s[p.collection].push(p.after)}P.validate(s);
 for(const p of patches){const data=p.after?structuredClone(p.after):null;if(p.collection==='transferHistory'&&data){data.by=u.name;data.byId=u.id;data.time=new Date().toISOString()}if(['learnerNotes','services'].includes(p.collection)&&data&&!p.before){data.owner=u.name;data.createdAt=new Date().toISOString()}if(p.collection==='assignments'&&data){data.by=u.name;data.time=new Date().toISOString()}if(p.collection==='roleOptions'){tx.set(db.doc('settings/roleOptions'),s.roleOptions);tx.set(db.collection('audit').doc(),stamp(u,{entity:'roleSettings',record:p.id,action:'修改',fields:Object.keys(p.after||{}),before:p.before||null,after:p.after||null}));continue}const ref=db.doc(p.collection+'/'+p.id);if(data)tx.set(ref,data);else tx.delete(ref);const fields=[...new Set([...Object.keys(p.before||{}),...Object.keys(data||{})])].filter(k=>!P.eq(p.before?.[k],data?.[k]));tx.set(db.collection('audit').doc(),stamp(u,{entity:p.collection,record:p.id,action:!p.before?'新增':!data?'删除':'修改',fields,before:p.before||null,after:data}));}
 });for(const id of new Set(disabled)){await auth.updateUser(id,{disabled:true});await auth.revokeRefreshTokens(id)}return {ok:true}}
async function createStaff(u,data){if(!P.ADMIN.includes(u.role))throw new HttpsError('permission-denied','只有老板和 Account 可以开通账号');const {email,password,name,role}=data;if(typeof email!=='string'||!/^\S+@\S+\.\S+$/.test(email)||typeof password!=='string'||password.length<12||password.length>128||typeof name!=='string'||!name.trim()||name.length>100||!P.ROLES.includes(role))throw new HttpsError('invalid-argument','请填写有效 Email、姓名、角色及至少12位密码');let created;try{created=await auth.createUser({email:email.trim().toLowerCase(),password,displayName:name.trim()});const profile={id:created.uid,email:created.email,name:name.trim(),role,inactive:false};await db.runTransaction(async tx=>{const actor=await tx.get(db.doc('users/'+u.id));if(!actor.exists||actor.data().inactive||!P.ADMIN.includes(actor.data().role))throw Error('权限已撤回');tx.create(db.doc('users/'+created.uid),profile);tx.set(db.collection('audit').doc(),stamp(u,{entity:'users',record:created.uid,action:'新增',fields:['name','email','role'],before:null,after:profile}));});return {ok:true}}catch(e){if(created)await auth.deleteUser(created.uid);if(e.code==='auth/email-already-exists')throw new HttpsError('already-exists','此 Email 已有 Firebase 账号，请联系老板检查');throw e}}
exports.crmApi=onCall({region:'asia-southeast1',enforceAppCheck:true,maxInstances:3,concurrency:20,timeoutSeconds:60,memory:'256MiB',cors:['https://maction-crm.web.app','https://maction-crm.firebaseapp.com','https://www.mustaction.my','https://mustaction.my',/^https:\/\/maction-crm--[a-z0-9-]+\.web\.app$/]},async req=>{try{const u=await actor(req),data=req.data||{};if(data.action==='load')return await load(u);if(data.action==='mutate')return await mutate(u,data.patches);if(data.action==='createStaff')return await createStaff(u,data);if(data.action==='login'){await db.collection('loginLogs').add(stamp(u,{action:'登录成功',mode:'Firebase Authentication'}));return {ok:true}}if(data.action==='logout'){await db.collection('loginLogs').add(stamp(u,{action:'退出账号',mode:'Firebase Authentication'}));return {ok:true}}throw new HttpsError('invalid-argument','操作无效')}catch(e){if(e instanceof HttpsError)throw e;console.error('CRM operation rejected',{code:e.code||'validation',message:e.message});throw new HttpsError('failed-precondition',e.code?.startsWith('auth/')?'账号操作失败，请检查 Email 或密码':e.message||'操作失败')}});
