'use strict';
const DATA=['clients','products','orders','payments','activities','events','learners','learnerNotes','services'];
const ACCESS=['assignments','transferHistory'];
const ADMIN=['老板','Account'];
const ROLES=[...ADMIN,'经理','团队'];
const idOK=id=>typeof id==='string'&&/^[\p{L}\p{N}_.:-]{1,128}$/u.test(id);
const eq=(a,b)=>JSON.stringify(canonical(a))===JSON.stringify(canonical(b));
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v}
const defaults={viewClients:true,viewOrders:true,viewCourses:true,viewServices:true,editFollowups:true,editDelivery:true,assign:true};
function capability(s,u,k){return ADMIN.includes(u.role)||((s.roleOptions?.[u.role]||{})[k]??(k==='assign'?u.role==='经理':defaults[k]))}
function service(s,o){const p=s.products.find(p=>p.id===o.product);return p?.type==='服务'||p?.category==='顾问服务'}
function ownsClient(s,u,id){return s.assignments.some(a=>a.user===u.id&&a.kind==='client'&&a.target===id)}
function ownsOrder(s,u,o){return s.assignments.some(a=>a.user===u.id&&a.kind==='order'&&a.target===o.id)||(!service(s,o)&&ownsClient(s,u,o.client))}
function scope(s,u){const out=structuredClone(s);if(u.role==='团队'){out.orders=s.orders.filter(o=>ownsOrder(s,u,o));const orders=new Set(out.orders.map(o=>o.id)),clients=new Set(out.orders.map(o=>o.client));s.clients.filter(c=>ownsClient(s,u,c.id)).forEach(c=>clients.add(c.id));out.clients=s.clients.filter(c=>clients.has(c.id));out.payments=s.payments.filter(p=>orders.has(p.order));out.learners=s.learners.filter(l=>l.order?orders.has(l.order):ownsClient(s,u,l.client));const learners=new Set(out.learners.map(l=>l.id));out.learnerNotes=s.learnerNotes.filter(n=>n.order?orders.has(n.order):learners.has(n.learner));out.services=s.services.filter(n=>learners.has(n.learner));out.activities=s.activities.filter(a=>clients.has(a.client));out.assignments=s.assignments.filter(a=>a.user===u.id);out.transferHistory=[];}
 for(const [permission,keys] of Object.entries({viewClients:['clients','activities'],viewOrders:['orders','payments'],viewCourses:['learners','events','learnerNotes'],viewServices:['services']})){if(!capability(s,u,permission))for(const key of keys)out[key]=[]}
 out.users=s.users.filter(x=>!x.inactive||u.role!=='团队').map(x=>({id:x.id,name:x.name,role:x.role,inactive:!!x.inactive,...(ADMIN.includes(u.role)?{email:x.email||''}:{})}));return out}
function authorizePatch(s,u,p){const {collection:k,id,before,after}=p;if(![...DATA,...ACCESS,'users','roleOptions'].includes(k)||!idOK(id))throw Error('无效资料类别或编号');const admin=ADMIN.includes(u.role),manager=u.role==='经理';if(k==='users'||k==='roleOptions'){if(!admin)throw Error('没有员工或角色权限');if(k==='users'&&(!before||!after))throw Error('请使用员工账号管理接口');if(k==='users'&&Object.keys(after).some(key=>!['id','name','email','role','inactive'].includes(key)))throw Error('员工字段无效');if(k==='users'&&after.email!==before.email)throw Error('不能直接修改登录 Email');return}
 if(k==='payments'&&!admin)throw Error('只有老板和 Account 可以更新收款');if(k==='clients'&&!after&&!admin)throw Error('只有老板和 Account 可以删除客户');
 if(ACCESS.includes(k)){if(u.role==='团队')throw Error('团队不能转交或分配资料');if(!capability(s,u,'assign'))throw Error('没有转交或分配权限');if(k==='transferHistory'&&(before||!after))throw Error('转交历史不可覆盖或删除');return}
 if(admin||manager){if(manager&&['learners','orders','services'].includes(k)&&!capability(s,u,'editDelivery'))throw Error('没有交付更新权限');if(manager&&['activities','learnerNotes'].includes(k)&&!capability(s,u,'editFollowups'))throw Error('没有跟进权限');return}
 if(!after)throw Error('团队不能删除资料');if(['clients','products','events','payments'].includes(k))throw Error('团队不能修改此资料');const r=before||after;const order=id=>s.orders.find(o=>o.id===id);const ownedOrder=id=>{const o=order(id);return o&&ownsOrder(s,u,o)};const ownedLearner=id=>{const l=s.learners.find(l=>l.id===id);return l&&(l.order?ownedOrder(l.order):ownsClient(s,u,l.client))};
 if(k==='orders'){if(!before||!ownedOrder(id)||!capability(s,u,'editDelivery'))throw Error('订单未分配或没有更新权限');const fields=['delivery','courseStatus','event','nextEvent','attendedDate','courseNote','stage','progress','satisfaction','serviceNext','serviceHistory','milestones'];if(Object.keys({...before,...after}).some(key=>!eq(before[key],after[key])&&!fields.includes(key)))throw Error('团队不能修改订单金额或归属');}
 else if(k==='learners'){if(!capability(s,u,'editDelivery')||!(r.order?ownedOrder(r.order):ownsClient(s,u,r.client)))throw Error('学员未分配');if(before&&(after.client!==before.client||after.order!==before.order))throw Error('团队不能转移学员归属');}
 else if(k==='learnerNotes'){if(!capability(s,u,'editFollowups')||!(r.order?ownedOrder(r.order):ownedLearner(r.learner)))throw Error('没有此跟进记录权限');if(before)throw Error('团队不能覆盖已有跟进记录');}
 else if(k==='services'){if(!capability(s,u,'editDelivery')||(!ownedLearner(r.learner)||!ownedLearner(after.learner)))throw Error('没有服务更新权限');if(before&&after.learner!==before.learner)throw Error('团队不能转移服务归属');}
 else if(k==='activities'){const visible=s.orders.some(o=>o.client===r.client&&ownsOrder(s,u,o))||ownsClient(s,u,r.client);if(!capability(s,u,'editFollowups')||!visible)throw Error('客户未分配');if(before&&after.client!==before.client)throw Error('不能更改跟进客户');}
 else throw Error('无此操作权限');
}
function validate(s){checkValue(s.roleOptions);for(const [role,options] of Object.entries(s.roleOptions||{})){if(!['经理','团队'].includes(role)||!options||typeof options!=='object'||Array.isArray(options)||Object.entries(options).some(([key,value])=>!Object.hasOwn(defaults,key)||typeof value!=='boolean'))throw Error('角色权限格式无效')}const exists=(k,id)=>s[k].some(r=>r.id===id);for(const k of [...DATA,...ACCESS,'users']){if(!Array.isArray(s[k]))throw Error('缺少资料表');const ids=new Set();for(const r of s[k]){if(!idOK(r.id)||ids.has(r.id))throw Error('记录编号无效或重复');ids.add(r.id);if(JSON.stringify(r).length>40000)throw Error('单条资料过大');checkValue(r)}}
 for(const c of s.clients)if(!c.name||!c.company||!['个人','公司'].includes(c.invoice)||!['YES','NO'].includes(c.hrdc))throw Error('客户资料不完整');
 for(const p of s.products)if(!p.name||!Number.isSafeInteger(p.price)||p.price<0)throw Error('产品资料无效');
 for(const o of s.orders)if(!exists('clients',o.client)||!exists('products',o.product)||!Number.isSafeInteger(o.total)||o.total<=0||['event','nextEvent'].some(k=>o[k]&&!s.events.some(e=>e.id===o[k]&&(e.products||[e.product]).includes(o.product))))throw Error('订单关联或金额无效');
 for(const p of s.payments)if(!exists('orders',p.order)||!Number.isSafeInteger(p.amount)||p.amount<=0)throw Error('付款无效');for(const o of s.orders)if(s.payments.filter(p=>p.order===o.id).reduce((n,p)=>n+p.amount,0)>o.total)throw Error('付款超过订单金额');
 for(const e of s.events)if(!e.name||!/^\d{4}-\d{2}-\d{2}$/.test(e.start)||!/^\d{4}-\d{2}-\d{2}$/.test(e.end)||e.end<e.start||!e.timeStart||e.timeEnd<=e.timeStart||(e.products||[e.product]).some(id=>!exists('products',id)))throw Error('活动资料无效');
 for(const l of s.learners)if(!l.name||!exists('clients',l.client)||l.order&&!s.orders.some(o=>o.id===l.order&&o.client===l.client)||['event','nextEvent'].some(k=>l[k]&&!s.events.some(e=>e.id===l[k]&&(!l.order||(e.products||[e.product]).includes(s.orders.find(o=>o.id===l.order)?.product)))))throw Error('学员关联无效');
 for(const a of s.activities)if(!a.text||!exists('clients',a.client)||a.event&&!exists('events',a.event))throw Error('客户跟进无效');
 for(const n of s.learnerNotes)if(!n.text||(!n.order&&!n.learner)||n.order&&!exists('orders',n.order)||n.learner&&!exists('learners',n.learner)||n.order&&n.learner&&!s.learners.some(l=>l.id===n.learner&&l.order===n.order)||n.event&&!exists('events',n.event))throw Error('跟进关联无效');
 for(const n of s.services)if(!n.text||!exists('learners',n.learner))throw Error('后续服务无效');
 for(const a of s.assignments)if(!s.users.some(u=>u.id===a.user&&u.role==='团队'&&!u.inactive)||!['client','order'].includes(a.kind)||!exists(a.kind==='client'?'clients':'orders',a.target))throw Error('分配对象无效');
 for(const u of s.users)if(!ROLES.includes(u.role)||!u.name)throw Error('员工资料无效');
}
function checkValue(v,depth=0){if(depth>10)throw Error('资料层数过多');if(typeof v==='string'&&v.length>10000)throw Error('文字内容过长');if(v&&typeof v==='object'){if(Array.isArray(v)&&v.length>500)throw Error('单条历史过多');for(const [k,x] of Object.entries(v)){if(['__proto__','prototype','constructor','password','refreshToken','idToken'].includes(k))throw Error('不允许的字段');checkValue(x,depth+1)}}else if(v!==null&&!['string','number','boolean','undefined'].includes(typeof v))throw Error('字段格式无效');if(typeof v==='number'&&!Number.isFinite(v))throw Error('数字无效')}
module.exports={DATA,ACCESS,ADMIN,ROLES,eq,scope,capability,authorizePatch,validate,idOK};
