// Local audit and login-design preview. No passwords are collected by the preview.
let auditRecords;try{auditRecords=typeof window!=='undefined'&&window.MACTION_INITIAL?window.MACTION_INITIAL.audit:JSON.parse(localStorage.getItem('maction-audit-demo'))||[]}catch{auditRecords=[]}
const auditLabels={clients:'客户',orders:'订单',payments:'收款',products:'产品',events:'课程活动',learners:'学员',activities:'客户跟进 / 重点事项',learnerNotes:'学员跟进',services:'后续服务',assignments:'资料分配',users:'员工权限',roleSettings:'角色逐项权限'};
let auditSnapshot=structuredClone(fullDb),accessSnapshot=structuredClone({assignments:access.assignments,users:access.users,roleSettings:Object.entries(access.roleOptions||{}).map(([id,settings])=>({id,...settings}))});
function recordAuditChanges(before,after){if(typeof window!=='undefined'&&window.MACTION_PRODUCTION)return;for(const key of Object.keys(auditLabels)){const oldRows=before[key]||[],newRows=after[key]||[];const index=rows=>new Map(rows.map((r,i)=>[r.id||`${key}:${i}`,r]));const old=index(oldRows),fresh=index(newRows);for(const id of new Set([...old.keys(),...fresh.keys()])){const a=old.get(id),b=fresh.get(id);if(JSON.stringify(a)===JSON.stringify(b))continue;const fields=[...new Set([...Object.keys(a||{}),...Object.keys(b||{})])].filter(f=>JSON.stringify(a?.[f])!==JSON.stringify(b?.[f]));auditRecords.push({id:crypto.randomUUID(),time:new Date().toISOString(),user:currentStaff.name,userId:currentStaff.id,role:currentStaff.role,entity:key,record:id,action:!a?'新增':!b?'删除':'修改',fields,before:a||null,after:b||null,mode:'本机预览日志'})}}localStorage.setItem('maction-audit-demo',JSON.stringify(auditRecords))}
const beforeAuditedSave=save;save=function(){beforeAuditedSave();recordAuditChanges(auditSnapshot,fullDb);auditSnapshot=structuredClone(fullDb)};
const beforeAuditedAccess=storeAccess;storeAccess=function(){const now={assignments:access.assignments,users:access.users,roleSettings:Object.entries(access.roleOptions||{}).map(([id,settings])=>({id,...settings}))};recordAuditChanges(accessSnapshot,now);accessSnapshot=structuredClone(now);beforeAuditedAccess()};
names.audit=['▤','操作审计'];navGroups[navGroups.length-1][1].push('audit');
const beforeAuditRender=render;render=function(){if(view==='audit'&&!admin())view='dashboard';if(view==='audit'){const actual=view;view='loginLogs';beforeAuditRender();view=actual;$('#crumb').textContent='操作审计';$('#main').innerHTML=heading('操作审计','查看每位员工新增、填写和更新的内容，以及修改前后的记录。')+`<div class="notice">当前为本浏览器的预览日志。正式系统需要在服务器记录账号、时间及修改内容，并禁止普通用户修改或删除日志。</div><section class="panel"><div class="toolbar"><input id="audit-search" class="search" placeholder="搜索员工、资料类型、记录或操作"><select id="audit-action"><option value="">全部操作</option><option>新增</option><option>修改</option><option>删除</option></select></div>${table(['时间（马来西亚）','员工 / 角色','资料类型','操作','记录','内容'],[...auditRecords].reverse().map(r=>`<tr data-audit-row data-action="${r.action}"><td>${esc(new Date(r.time).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur'}))}</td><td>${esc(r.user)}<p>${esc(r.role)}</p></td><td>${esc(auditLabels[r.entity])}</td><td>${badge(r.action,r.action==='删除'?'red':'gray')}</td><td>${esc(r.record)}</td><td><button class="link" data-audit-detail="${r.id}">查看修改前后</button><p>${esc(r.fields.join('、'))}</p></td></tr>`))}</section>`}else beforeAuditRender();document.querySelectorAll('#nav [data-view="audit"]').forEach(b=>b.hidden=!admin());const logout=document.createElement('button');logout.className='button small';logout.dataset.previewLogout='1';logout.textContent='退出 / 登录页';$('.header-right').append(logout)};
function auditFilter(){const query=($('#audit-search')?.value||'').toLowerCase(),action=$('#audit-action')?.value||'';document.querySelectorAll('[data-audit-row]').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(query)||(action&&row.dataset.action!==action))}
document.addEventListener('input',e=>{if(e.target.id==='audit-search')auditFilter()});document.addEventListener('change',e=>{if(e.target.id==='audit-action')auditFilter()});
function showLogin(){if(typeof window!=='undefined'&&window.MACTION_PRODUCTION){window.location.href='/firebase-login.html';return}let page=$('#login-preview');if(!page){page=document.createElement('section');page.id='login-preview';document.body.append(page)}page.innerHTML=`<div class="login-brand-panel"><img src="login-brand.png" alt="MACTION 金色 Logo，连锁、绩效、资本"><p>MACTION CUSTOMER RELATIONSHIP MANAGEMENT</p></div><div class="login-card"><span class="login-kicker">MACTION CRM</span><h1>欢迎回来</h1><p>客户、课程与服务管理中心</p><form id="preview-login-form"><label for="login-user">选择预览账号</label><select id="login-user" name="user">${access.users.map(u=>`<option value="${esc(u.id)}">${esc(u.name)} · ${esc(u.role)}</option>`).join('')}</select><button type="submit" class="login-submit">进入系统预览</button></form><div class="login-preview-note">登录界面预览 · 尚未连接真实账号验证</div></div><span class="login-footer">连锁 · 绩效 · 资本</span>`;page.hidden=false;document.body.classList.add('login-visible')}
permissionEventRoot.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if((b.hasAttribute('data-delete-client')||b.hasAttribute('data-client-delete'))&&!admin()){e.preventDefault();e.stopImmediatePropagation();return toast('经理和团队不能删除客户记录')}if(b.hasAttribute('data-preview-logout')){if(typeof window!=='undefined'&&window.MACTION_PRODUCTION){e.preventDefault();e.stopImmediatePropagation();showLogin();return}logDemo('退出预览会话');showLogin()}if(b.dataset.auditDetail){if(!admin())return;const r=auditRecords.find(r=>r.id===b.dataset.auditDetail);modal('修改前 / 修改后',`<div class="modal-body"><h3>${esc(r.user)} · ${esc(r.action)}${esc(auditLabels[r.entity])}</h3><p>${esc(r.record)} · ${esc(r.time)}</p>${table(['字段','修改前','修改后'],r.fields.map(k=>`<tr><td>${esc(k)}</td><td style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(typeof r.before?.[k]==='object'?JSON.stringify(r.before[k]):r.before?.[k]??'—')}</td><td style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(typeof r.after?.[k]==='object'?JSON.stringify(r.after[k]):r.after?.[k]??'—')}</td></tr>`))}</div>`) }},true);
permissionEventRoot.addEventListener('submit',e=>{if(['delete-client-form','client-delete-form'].includes(e.target.id)&&!admin()){e.preventDefault();e.stopImmediatePropagation();return toast('经理和团队不能删除客户记录')}if(e.target.id!=='preview-login-form')return;e.preventDefault();e.stopImmediatePropagation();const u=access.users.find(u=>u.id===new FormData(e.target).get('user'));if(!u)return;currentStaff=u;db=fullDb;logDemo('进入预览会话（非真实登录）');$('#login-preview').hidden=true;document.body.classList.remove('login-visible');view='dashboard';render()},true);
render();if(!(typeof window!=='undefined'&&window.MACTION_PRODUCTION))showLogin();

