const bulkSchemas={
clients:{title:'客户资料',columns:[...clientColumns,'industry','companySize','branches','businessStage','businessProblem','growthGoal'],required:['id','name'],sample:{id:'IMPORT-C001',name:'测试客户',company:'测试公司',phone:'0123456789',invoice:'公司',hrdc:'NO',owner:'Amanda'}},
products:{title:'课程与服务产品',columns:['id','name','type','category','priceRM','description'],required:['id','name','type','priceRM'],sample:{id:'IMPORT-P001',name:'企业连锁课程',type:'课程',category:'企业培训',priceRM:'6800'}},
orders:{title:'购买订单',columns:['id','client','product','totalRM','date','due','salesOwner','delivery','courseStatus','event','nextEvent','attendedDate','courseNote','stage','progress','satisfaction'],required:['id','client','product','totalRM','date'],sample:{id:'IMPORT-O001',client:'IMPORT-C001',product:'IMPORT-P001',totalRM:'6800',date:'2026-10-01',salesOwner:'Amanda',delivery:'待安排'}},
payments:{title:'付款记录',columns:['id','order','amountRM','date','method','note'],required:['id','order','amountRM','date'],sample:{id:'IMPORT-PAY001',order:'IMPORT-O001',amountRM:'2000',date:'2026-10-01',method:'Bank Transfer',note:'Deposit'}},
events:{title:'课程活动',columns:['id','name','products','start','end','timeStart','timeEnd','venue','teacher'],required:['id','name','products','start','end','timeStart','timeEnd'],sample:{id:'IMPORT-E001',name:'企业连锁实战班',products:'IMPORT-P001',start:'2026-10-20',end:'2026-10-23',timeStart:'10:00',timeEnd:'18:00',venue:'M World Hotel',teacher:'Dr Jacky Lim'}},
learners:{title:'学员报名',columns:['id','client','name','ic','phone','email','position','event','nextEvent','order','status','serviceStatus'],required:['id','client','name'],sample:{id:'IMPORT-L001',client:'IMPORT-C001',name:'测试学员',order:'IMPORT-O001',event:'IMPORT-E001',status:'还没上课',serviceStatus:'暂无后续服务'}},
activities:{title:'客户跟进',columns:['id','client','date','channel','text','next','owner','event','done'],required:['id','client','date','text'],sample:{id:'IMPORT-A001',client:'IMPORT-C001',date:'2026-10-02',channel:'电话',text:'已确认报名',owner:'Amanda',done:'NO'}},
learnerNotes:{title:'学员跟进',columns:['id','learner','date','channel','text','next','owner'],required:['id','learner','date','text'],sample:{id:'IMPORT-N001',learner:'IMPORT-L001',date:'2026-10-03',text:'已确认上课时间',channel:'WhatsApp',owner:'Amanda'}},
services:{title:'学员后续服务记录',columns:['id','learner','name','date','status','text','owner'],required:['id','learner','name','date','status','text'],sample:{id:'IMPORT-S001',learner:'IMPORT-L001',name:'课后辅导',date:'2026-10-25',status:'进行中',text:'讨论实际经营问题',owner:'Amanda'}}};
const bulkColumnTitles={id:'唯一记录编号',name:'名称',ic:'身份证号码 IC No.',phone:'电话号码 Phone No.',email:'电子邮箱 Email',position:'职位 Position',company:'公司名称 Company Name',reg:'公司注册号码 Company Register No.',address:'公司地址 Company Address',tin:'公司税号 Company TIN No.',sst:'公司 SST No.',invoice:'发票对象（公司 / 个人）',hrdc:'HRDC Claim（YES / NO）',owner:'负责人',industry:'行业',companySize:'企业规模 / 员工人数',branches:'分店数量',businessStage:'企业经营阶段',businessProblem:'目前经营问题',growthGoal:'想达到的目标',type:'产品类型（课程 / 服务）',category:'产品分类',priceRM:'产品参考价格（RM）',description:'产品说明',client:'关联客户编号',product:'关联产品编号',totalRM:'订单成交金额（RM）',date:'记录日期（YYYY-MM-DD）',due:'付款到期日（YYYY-MM-DD）',salesOwner:'销售负责人',delivery:'交付状态（待安排 / 已安排 / 进行中 / 已完成 / 已取消）',courseStatus:'上课情况（还没上课 / 已安排上课 / 已上课 / 缺席 / 已改期）',event:'关联活动编号',nextEvent:'下一期活动编号',attendedDate:'实际参加日期（YYYY-MM-DD）',courseNote:'课程后续情况 / 备注',stage:'服务阶段（待启动 / 需求确认 / 方案制定 / 执行中 / 验收中 / 已完成）',progress:'服务完成进度（0–100）',satisfaction:'满意度（未评估 / 1–5）',order:'关联订单编号',amountRM:'本次收款金额（RM）',method:'付款方式',note:'付款备注 / 参考号码',products:'关联产品编号（多个用 | 分隔）',start:'活动开始日期（YYYY-MM-DD）',end:'活动结束日期（YYYY-MM-DD）',timeStart:'每天开始时间（HH:MM）',timeEnd:'每天结束时间（HH:MM）',venue:'活动地点',teacher:'授课老师',status:'状态',serviceStatus:'后续服务状态',channel:'联系渠道',text:'沟通 / 服务内容',next:'下次跟进日期（YYYY-MM-DD）',done:'跟进已完成（YES / NO）',learner:'关联学员编号'};
function bulkColumnTitle(key,column){if(column==='name')return ({clients:'个人全名 Full Name',products:'课程 / 服务产品名称',events:'实际课程活动名称',learners:'学员姓名',services:'后续服务名称'})[key]||'名称';if(column==='status')return key==='learners'?'上课状态（还没上课 / 已上课 / 缺席 / 已改期）':'服务状态（待安排 / 进行中 / 已完成）';return bulkColumnTitles[column]||column}
function bulkTemplateCSV(key){const s=bulkSchemas[key],headers=s.columns.map(k=>`${bulkColumnTitle(key,k)} [${k}]${s.required.includes(k)?' *必填':''}`);return '\ufeff'+[headers.map(csvCell).join(','),s.columns.map(k=>csvCell(s.sample[k]||'')).join(',')].join('\r\n')}
function bulkHeaderKey(header){const trimmed=header.trim(),match=trimmed.match(/\[([A-Za-z][A-Za-z0-9]*)\]/);return match?match[1]:trimmed}
function bulkMoney(value,label){if(!/^\d+(\.\d{1,2})?$/.test(String(value)))throw Error(label+' 金额须为非负数字，最多两位小数');const cents=Math.round(Number(value)*100);if(!Number.isSafeInteger(cents))throw Error(label+' 金额过大');return cents}
function validImportDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value}
function normalizeBulkRow(key,row,line){const s=bulkSchemas[key],out=Object.fromEntries(s.columns.filter(k=>row[k]!==undefined&&row[k]!=='').map(k=>[k,String(row[k]).trim()]));for(const k of s.required)if(!out[k])throw Error(`${s.title} 第 ${line} 行缺少 ${k}`);for(const k of ['date','due','start','end','next','attendedDate'])if(out[k]&&!validImportDate(out[k]))throw Error(`${s.title} 第 ${line} 行 ${k} 必须为有效 YYYY-MM-DD`);if(key==='clients'){out.invoice??='公司';out.hrdc??='NO';out.company??=out.invoice==='个人'?'个人客户':'';out.owner??='未分配'}if(key==='products'){if(!['课程','服务'].includes(out.type))throw Error('产品 type 必须为课程或服务');out.price=bulkMoney(out.priceRM,s.title);delete out.priceRM;out.category??=out.type==='服务'?'顾问服务':'企业培训'}if(key==='orders'){out.total=bulkMoney(out.totalRM,s.title);delete out.totalRM;out.delivery??='待安排';out.salesOwner??='未分配';if(!['待安排','已安排','进行中','已完成','已取消'].includes(out.delivery))throw Error('订单交付状态无效');if(out.progress!==undefined){out.progress=Number(out.progress);if(!Number.isInteger(out.progress)||out.progress<0||out.progress>100)throw Error('服务进度须为0–100整数')}}if(key==='payments'){out.amount=bulkMoney(out.amountRM,s.title);delete out.amountRM;out.method??='Bank Transfer'}if(key==='events'){out.products=[...new Set(out.products.split('|').map(x=>x.trim()).filter(Boolean))];out.product=out.products[0];if(!/^\d{2}:\d{2}$/.test(out.timeStart)||!/^\d{2}:\d{2}$/.test(out.timeEnd))throw Error('活动时间须为 HH:MM')}if(key==='learners'){out.status??='还没上课';out.serviceStatus??='暂无后续服务'}if(key==='activities'){if(out.done&&!['YES','NO'].includes(out.done))throw Error('done 须为 YES 或 NO');out.done=out.done==='YES';out.channel??='电话';out.owner??='未分配'}return out}
function planBulkImport(batches,base=db){const candidate=structuredClone(base),summary=[],seenFiles=new Set();for(const {key,rows} of batches){if(!bulkSchemas[key]||seenFiles.has(key))throw Error('每一类只允许一个文件');seenFiles.add(key);let added=0,skipped=0;const seen=new Set((candidate[key]||[]).map(r=>r.id).filter(Boolean));for(const [i,row] of rows.entries()){const record=normalizeBulkRow(key,row,i+2);if(seen.has(record.id)){const existing=candidate[key].find(r=>r.id===record.id);const comparable=normalizeBulkRow(key,bulkExportRecord(key,existing),i+2);if(Object.entries(record).some(([k,v])=>JSON.stringify(comparable[k])!==JSON.stringify(v)))throw Error(`${bulkSchemas[key].title} ${record.id} 已存在但内容不同，请使用新编号或编辑现有资料`);skipped++;continue}seen.add(record.id);candidate[key].push(record);added++}summary.push({key,added,skipped})}validateBackup(candidate);for(const l of candidate.learners){const o=candidate.orders.find(o=>o.id===l.order);if(l.event&&o&&!eventMatchesProduct(candidate.events.find(e=>e.id===l.event),o.product))throw Error('学员 '+l.id+' 的活动不属于购买产品')}return {candidate,summary}}

function bulkExportRecord(key,record,index=0){const r={...record};r.id||=(key+'-export-'+index);if(key==='products'){r.priceRM=(r.price/100).toFixed(2);r.type??=productIsService(r)?'服务':'课程'}if(key==='orders')r.totalRM=(r.total/100).toFixed(2);if(key==='payments')r.amountRM=(r.amount/100).toFixed(2);if(key==='events')r.products=eventProducts(r).join('|');if(key==='activities')r.done=r.done?'YES':'NO';return Object.fromEntries(bulkSchemas[key].columns.map(c=>[c,r[c]??'']))}
function unifiedExportCSV(data=db){const columns=Object.entries(bulkSchemas).flatMap(([key,s])=>s.columns.map(column=>({key,column})));const header=parseCSV(unifiedTemplateCSV())[0];const rows=Object.entries(bulkSchemas).flatMap(([key])=>(data[key]||[]).map((r,i)=>{const record=bulkExportRecord(key,r,i);return columns.map(c=>csvCell(c.key===key?record[c.column]:'' )).join(',')}));return '\ufeff'+[header.map(csvCell).join(','),...rows].join('\r\n')}
const beforeLatestExport=exportData;exportData=function(kind){if(kind==='template')return download('maction-all-in-one.csv',unifiedTemplateCSV(),'text/csv;charset=utf-8');if(bulkSchemas[kind]){const schema=bulkSchemas[kind],headers=schema.columns.map(c=>bulkColumnTitle(kind,c)+' ['+c+']');return download('maction-'+kind+'.csv','\ufeff'+[headers.map(csvCell).join(','),...db[kind].map((r,i)=>{const record=bulkExportRecord(kind,r,i);return schema.columns.map(c=>csvCell(record[c])).join(',')})].join('\r\n'),'text/csv;charset=utf-8')}return beforeLatestExport(kind)};
permissionEventRoot.addEventListener('click',e=>{if(!e.target.closest('[data-unified-export]'))return;e.preventDefault();e.stopImmediatePropagation();if(!canData())return toast('只有老板和Account可以导出');download('maction-all-data-'+today()+'.csv',unifiedExportCSV(),'text/csv;charset=utf-8')},true);
function unifiedTemplateCSV(){const columns=Object.entries(bulkSchemas).flatMap(([key,s])=>s.columns.map(column=>({key,column})));return '\ufeff'+[columns.map(({key,column})=>csvCell(bulkSchemas[key].title+' · '+bulkColumnTitle(key,column)+' ['+key+'.'+column+']'+(bulkSchemas[key].required.includes(column)?' *必填':''))).join(','),columns.map(({key,column})=>csvCell(bulkSchemas[key].sample[column]||'')).join(',')].join('\r\n')}
function unifiedHeaderKey(header){const h=header.trim(),match=h.match(/\[([A-Za-z]+)\.([A-Za-z][A-Za-z0-9]*)\]/);if(match)return match[1]+'.'+match[2];for(const [key,s] of Object.entries(bulkSchemas))for(const column of s.columns)if(h===key+'.'+column||h===s.title+' · '+bulkColumnTitle(key,column))return key+'.'+column;return null}
function readUnifiedCSV(text){const parsed=parseCSV(text),raw=parsed.shift()||[];if(!raw.some(h=>unifiedHeaderKey(h)))return null;const headers=raw.map(unifiedHeaderKey);if(headers.some(h=>!h)||new Set(headers).size!==headers.length)throw Error('完整模板有未知或重复标题，请保留模板标题');for(const h of headers){const [key,column]=h.split('.');if(!bulkSchemas[key]?.columns.includes(column))throw Error('不支持的完整模板标题 '+h)}const groups=Object.fromEntries(Object.keys(bulkSchemas).map(k=>[k,[]]));for(const [i,values] of parsed.entries()){if(values.every(v=>!v.trim()))continue;if(values.length!==headers.length)throw Error('完整模板第 '+(i+2)+' 行列数不符');const row=Object.fromEntries(headers.map((h,j)=>[h,values[j].trim()])),records={};for(const [key,s] of Object.entries(bulkSchemas)){const record=Object.fromEntries(s.columns.filter(c=>row[key+'.'+c]).map(c=>[c,row[key+'.'+c]]));if(Object.keys(record).length)records[key]=record;}const link=(key,column,source)=>{if(records[key]&&!records[key][column]&&records[source]?.id)records[key][column]=records[source].id};for(const k of ['orders','learners','activities'])link(k,'client','clients');link('orders','product','products');link('orders','event','events');link('payments','order','orders');link('learners','order','orders');link('learners','event','events');for(const k of ['learnerNotes','services'])link(k,'learner','learners');link('activities','event','events');if(records.events&&!records.events.products&&records.products?.id)records.events.products=records.products.id;for(const [key,r] of Object.entries(records)){if(Object.keys(r).length===1&&r.id&&(db[key].some(x=>x.id===r.id)||groups[key].some(x=>x.id===r.id)))continue;groups[key].push(r)}}return Object.entries(groups).filter(([,rows])=>rows.length).map(([key,rows])=>({key,rows}))}
permissionEventRoot.addEventListener('click',e=>{const b=e.target.closest('[data-unified-template]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(!canData())return toast('只有老板和Account可以下载');download('maction-all-in-one.csv',unifiedTemplateCSV(),'text/csv;charset=utf-8')},true);

let bulkPlan=null;
async function previewBulkFiles(){if(!canData())throw Error('当前角色不能导入资料');bulkPlan=null;const files=Array.from($('#bulk-files').files||[]);if(!files.length)throw Error('请先选择一个或多个分类CSV文件');if(files.reduce((s,f)=>s+f.size,0)>10*1024*1024)throw Error('总文件大小不能超过10MB');const batches=[];for(const file of files){if(files.length===1){const combined=readUnifiedCSV(await file.text());if(combined){batches.push(...combined);continue}}const key=file.name.replace(/\.csv$/i,'').replace(/^maction-/,'');if(!bulkSchemas[key])throw Error('未知文件名 '+file.name+'，请保留模板文件名');const rows=parseCSV(await file.text()),headers=(rows.shift()||[]).map(bulkHeaderKey);if(new Set(headers).size!==headers.length||headers.some(h=>!bulkSchemas[key].columns.includes(h)))throw Error(file.name+' 列名无效，请使用模板');const data=rows.map((row,i)=>{if(row.length!==headers.length)throw Error(file.name+' 第'+(i+2)+'行列数错误');return Object.fromEntries(headers.map((h,j)=>[h,row[j]]))});batches.push({key,rows:data})}bulkPlan=planBulkImport(batches);modal('确认批量导入历史资料',`<div class="modal-body"><div class="notice">仅新增合并，不替换现有资料。检查通过后确认才写入当前浏览器；云端数据尚未接入。</div>${table(['资料类别','新增','重复跳过'],bulkPlan.summary.map(s=>`<tr><td>${bulkSchemas[s.key].title}</td><td>${s.added}</td><td>${s.skipped}</td></tr>`))}<h3 style="margin-top:20px">本次新增订单摘要</h3>${table(['订单','客户','产品','订单金额'],bulkPlan.candidate.orders.filter(o=>!db.orders.some(x=>x.id===o.id)).slice(0,20).map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(bulkPlan.candidate.clients.find(c=>c.id===o.client)?.name)}</td><td>${esc(bulkPlan.candidate.products.find(p=>p.id===o.product)?.name)}</td><td>${rm(o.total)}</td></tr>`))}</div><div class="modal-footer"><button class="button" data-close>取消</button><button class="button primary" data-bulk-confirm>确认合并导入</button></div>`)}
const beforeBulkRender=render;render=function(){beforeBulkRender();if(view!=='data'||!canData())return;const panel=document.createElement('section');panel.className='panel';panel.style.marginBottom='24px';panel.innerHTML=`<div class="panel-head"><h2>一次批量导入 · 客户＋课程／服务＋付款记录</h2></div><div class="panel-body"><p>下载「一份完整模板」，在同一张表填写已有资料，另存为 UTF-8 CSV 后一次导入。空白资料区会跳过，不需要拆分文件。同一公司多位学员可分多行填写，使用相同客户／订单编号；后续行可只填写已在前面出现的编号。</p><p>客户 id → 订单 client；产品 id → 订单 product；订单 id → 付款 order。活动 products 可用 | 分隔多个产品编号。服务合同放 orders，后续学员服务放 services。</p><div class="actions" style="margin:18px 0;flex-wrap:wrap"><button class="button primary" data-unified-template>下载一份完整模板（全部资料）</button><button class="button" data-unified-export>导出全部资料（同格式单文件）</button><details><summary>分类模板</summary>${Object.entries(bulkSchemas).map(([key,s])=>`<button class="button small" data-bulk-template="${key}">${s.title}模板</button>`).join('')}</details></div><div class="notice">模板含一组关联示例。正式导入前替换或删除示例行；标题已包含中文名称、英文字段和必填标记；请保留完整标题。完整模板文件名可更改，栏目可调整顺序，不填写的栏目可删除。ID、电话、IC 请在 Excel 中设为文本，金额单位为 RM。</div><label for="bulk-files">选择完整模板 CSV（一次导入）</label><input id="bulk-files" type="file" accept=".csv" multiple style="display:block;width:100%;margin:10px 0"><button class="button primary" data-bulk-preview>检查并预览全部资料</button><p style="margin-top:12px">支持已有产品／客户编号；缺少关联、错误金额、超额付款或冲突编号会阻止整批导入。</p></div>`;$('#main .heading').after(panel)};
permissionEventRoot.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!b.dataset.bulkTemplate&&!b.hasAttribute('data-bulk-preview')&&!b.hasAttribute('data-bulk-confirm'))return;e.preventDefault();e.stopImmediatePropagation();if(!canData())return toast('只有老板和Account可以导入导出');try{if(b.dataset.bulkTemplate){const s=bulkSchemas[b.dataset.bulkTemplate];download(b.dataset.bulkTemplate+'.csv',bulkTemplateCSV(b.dataset.bulkTemplate),'text/csv;charset=utf-8')}if(b.hasAttribute('data-bulk-preview'))await previewBulkFiles();if(b.hasAttribute('data-bulk-confirm')){if(!bulkPlan)return;const plan=bulkPlan;bulkPlan=null;const valid=validateBackup(plan.candidate);db=valid;fullDb=db;save();$('#dialog').close();render();toast('全部历史资料已合并导入')}}catch(err){bulkPlan=null;toast(err.message||'导入失败')}} ,true);
render();

