let clientSort='az';
const beforeClientListRender=render;
function sortedClients(){return db.clients.filter(c=>[c.name,c.company,c.phone,c.email].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))&&(filter==='all'||c.hrdc===filter)).sort((a,b)=>{const result=a.name.localeCompare(b.name,'zh-Hans-u-co-pinyin',{sensitivity:'base',numeric:true});return clientSort==='za'?-result:result})}
render=function(){beforeClientListRender();if(view!=='clients')return;const list=sortedClients(),panel=$('#main .panel');panel.innerHTML=`<div class="toolbar"><input class="search" id="search" placeholder="搜索姓名、公司、电话或 Email" value="${esc(query)}"><div class="actions"><label for="client-sort">姓名排序</label><select id="client-sort"><option value="az" ${clientSort==='az'?'selected':''}>A–Z（中文按拼音）</option><option value="za" ${clientSort==='za'?'selected':''}>Z–A（中文按拼音）</option></select><select id="filter" aria-label="HRDC Claim 筛选"><option value="all">全部 HRDC 状态</option><option value="YES" ${filter==='YES'?'selected':''}>HRDC Claim · YES</option><option value="NO" ${filter==='NO'?'selected':''}>HRDC Claim · NO</option></select></div></div>${table(['No.','姓名 / 公司','联系方式','Invoice 对象','HRDC Claim','购买金额','负责人','操作'],list.map((c,i)=>`<tr><td class="client-no">${i+1}</td><td><div class="client-list-identity"><button class="link client-person-name" data-detail="${esc(c.id)}">${esc(c.name)}</button><label style="display:flex;align-items:center;gap:8px"><input type="checkbox" data-client-vip="${esc(c.id)}" ${c.vip?'checked':''} style="width:18px;height:18px"> ⭐ VIP</label><span class="client-company-name">${esc(c.company)}</span></div></td><td><div class="client-list-contact"><span>${esc(c.phone)}</span><span class="client-email">${esc(c.email)}</span></div></td><td>${esc(c.invoice)}</td><td>${badge(c.hrdc,c.hrdc==='YES'?'':'gray')}</td><td class="money">${rm(sum(db.orders.filter(o=>o.client===c.id).map(o=>o.total)))}</td><td>${esc(c.owner)}</td><td><button class="link" data-detail="${esc(c.id)}">客户档案</button></td></tr>`))}<div class="table-foot">${list.length} 位客户 · 姓名${clientSort==='az'?'升序':'降序'}</div>`;applyPageFilters()};
const beforeClientFilters=applyPageFilters;applyPageFilters=function(){beforeClientFilters();if(view==='clients'){let no=0;document.querySelectorAll('#main tbody tr').forEach(row=>{if(!row.hidden){const cell=row.querySelector('.client-no');if(cell)cell.textContent=++no}})}};
document.addEventListener('change',e=>{if(e.target.id==='client-sort'){clientSort=e.target.value;render()}});
render();

document.addEventListener('change',e=>{const id=e.target.dataset.clientVip;if(!id)return;if(currentStaff.role==='团队'){e.target.checked=!!client(id)?.vip;return toast('当前角色不能修改客户资料')}const c=client(id);if(!c)return;c.vip=e.target.checked;save();toast(c.vip?'已标记 ⭐ VIP':'已取消 VIP 标记')},true);
