const permissionEventRoot=typeof window!=='undefined'?window:document;
// Local role preview only. Production authorization must be enforced by Firebase, not this UI.
const staffSeed=[{id:'boss',name:'老板',role:'老板'},{id:'account',name:'Account',role:'Account'},{id:'manager',name:'经理',role:'经理'},{id:'amanda',name:'Amanda',role:'团队'},{id:'jason',name:'Jason',role:'团队'}];
let access;try{access=JSON.parse(localStorage.getItem('maction-access-demo'))}catch{}access??={users:staffSeed,assignments:[],logs:[]};let currentStaff=access.users[0],fullDb=db;
const admin=()=>['老板','Account'].includes(currentStaff.role),canAssign=()=>admin()||(currentStaff.role==='经理'&&(typeof allowedRoleOption!=='function'||allowedRoleOption('assign'))),canData=()=>admin();
function storeAccess(){localStorage.setItem('maction-access-demo',JSON.stringify(access))}
function assignedClient(id){return access.assignments.some(a=>a.user===currentStaff.id&&a.kind==='client'&&a.target===id)}
function assignedOrder(o){return assignedClient(o.client)||access.assignments.some(a=>a.user===currentStaff.id&&a.kind==='order'&&a.target===o.id)}
function scopedData(){if(currentStaff.role!=='团队')return fullDb;const orders=fullDb.orders.filter(assignedOrder),ids=new Set(orders.map(o=>o.id)),clientIds=new Set(orders.map(o=>o.client));fullDb.clients.filter(c=>assignedClient(c.id)).forEach(c=>clientIds.add(c.id));const learners=fullDb.learners.filter(l=>ids.has(l.order)||(!l.order&&assignedClient(l.client))),learnerIds=new Set(learners.map(l=>l.id));return {...fullDb,clients:fullDb.clients.filter(c=>clientIds.has(c.id)),orders,payments:fullDb.payments.filter(p=>ids.has(p.order)),learners,learnerNotes:fullDb.learnerNotes.filter(n=>learnerIds.has(n.learner)),services:fullDb.services.filter(s=>learnerIds.has(s.learner)),activities:fullDb.activities.filter(a=>assignedClient(a.client)||clientIds.has(a.client))}}
const priorSave=save;save=function(){if(currentStaff.role==='团队'){for(const k of ['activities','learnerNotes','services','learners'])for(const record of db[k])if(!fullDb[k].includes(record))fullDb[k].push(record);const scoped=db;db=fullDb;try{priorSave()}finally{db=scoped}}else{fullDb=db;priorSave()}storeAccess()};
names.permissions=['⚙','权限与分配'];names.loginLogs=['◷','登录记录'];navGroups.push(['系统管理',['permissions','loginLogs']]);
function logDemo(action,user=currentStaff){access.logs.push({id:crypto.randomUUID(),user:user.name,userId:user.id,role:user.role,time:new Date().toISOString(),action,mode:'角色模拟，非真实登录'});storeAccess()}
function staffSelect(){return `<label class="role-preview">角色预览<select id="staff-preview" aria-label="切换预览角色">${access.users.map(u=>`<option value="${esc(u.id)}" ${u.id===currentStaff.id?'selected':''}>${esc(u.name)} · ${esc(u.role)}</option>`).join('')}</select></label>`}
function assignmentForm(){modal('分配客户 / 课程或服务订单',`<form id="assignment-form"><div class="modal-body"><div class="notice">分配整个客户：团队可查看该客户全部订单。分配单个订单：团队可查看客户开票资料和该订单的交付、付款与学员记录。</div><div class="form-grid">${selectField('分配范围','kind',[['order','单个课程 / 服务订单'],['client','整个客户']])}${selectField('团队成员','user',access.users.filter(u=>u.role==='团队').map(u=>[u.id,u.name]))}${selectField('选择订单','target',fullDb.orders.map(o=>[o.id,client(o.client).name+' · '+product(o.product).name+' · '+o.id]))}</div></div>${controls}</form>`);$('#f-kind').onchange=()=>{$('#f-target').innerHTML=($('#f-kind').value==='client'?fullDb.clients.map(c=>[c.id,c.name+' · '+c.company]):fullDb.orders.map(o=>[o.id,client(o.client).name+' · '+product(o.product).name+' · '+o.id])).map(([id,label])=>`<option value="${esc(id)}">${esc(label)}</option>`).join('')};}
const beforePermissionsRender=render;render=function(){if(currentStaff.role==='团队')db=scopedData();if(!canData()&&view==='data')view='dashboard';if(!canAssign()&&['permissions','loginLogs'].includes(view))view='dashboard';if(['permissions','loginLogs'].includes(view)){const actual=view;view='clients';beforePermissionsRender();view=actual;$('#crumb').textContent=names[view][1];if(view==='permissions')$('#main').innerHTML=heading('权限与客户分配','经理分配客户或课程订单，团队仅查看自己的工作资料。',`<div class="actions">${admin()?'<button class="button" data-staff-new>＋ 添加员工</button>':''}<button class="button primary" data-assignment-new>＋ 分配资料</button></div>`)+`<div class="notice">目前为本机权限模拟。真实登录记录及服务器权限将在连接 Firebase 后生效。</div><section class="panel"><div class="panel-head"><h2>角色权限</h2></div>${table(['角色','资料范围','Import / Export','客户分配'],[['老板','全部资料','允许','允许'],['Account','全部资料','允许','允许'],['经理','全部客户与交付资料','禁止','允许'],['团队','仅分配客户 / 订单','禁止','禁止']].map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`))}</section><section class="panel" style="margin-top:24px"><div class="panel-head"><h2>当前分配记录</h2></div>${table(['团队成员','分配范围','客户 / 订单','分配人','操作'],access.assignments.map(a=>`<tr><td>${esc(access.users.find(u=>u.id===a.user)?.name)}</td><td>${a.kind==='client'?'整个客户':'单个订单'}</td><td>${esc(a.kind==='client'?fullDb.clients.find(c=>c.id===a.target)?.name:a.target)}</td><td>${esc(a.by)}</td><td><button class="link" data-unassign="${a.id}">取消分配</button></td></tr>`))}</section>`;else $('#main').innerHTML=heading('登录与操作记录','当前展示角色切换及权限操作的模拟记录。')+`<section class="panel">${table(['时间（马来西亚）','员工','角色','事件','记录类型'],[...access.logs].reverse().map(l=>`<tr><td>${esc(new Date(l.time).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur'}))}</td><td>${esc(l.user)}</td><td>${esc(l.role)}</td><td>${esc(l.action)}</td><td>${esc(l.mode)}</td></tr>`))}</section>`;}else beforePermissionsRender();const header=$('.header-right');header.innerHTML=staffSelect();document.querySelectorAll('#nav [data-view]').forEach(b=>{if((b.dataset.view==='data'&&!canData())||(['permissions','loginLogs'].includes(b.dataset.view)&&!canAssign()))b.hidden=true});if(!admin())document.querySelectorAll('[data-download],[data-import-csv],[data-import-json],#reset').forEach(b=>b.hidden=true);if(currentStaff.role==='团队')document.querySelectorAll('[data-new="order"],[data-new="client"],[data-pay],[data-product-new],[data-product-edit],[data-event-new],[data-event-edit]').forEach(b=>b.hidden=true)};
document.addEventListener('change',e=>{if(e.target.id==='staff-preview'){save();logDemo('结束角色预览');currentStaff=access.users.find(u=>u.id===e.target.value)||access.users[0];db=fullDb;logDemo('进入角色预览');view='dashboard';query='';filter='all';$('#dialog').close();render()}},true);
permissionEventRoot.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const forbidden=(!canData()&&(b.dataset.download||b.hasAttribute('data-import-csv')||b.hasAttribute('data-import-json')||b.hasAttribute('data-confirm-import')||b.id==='reset'))||(!canAssign()&&(b.hasAttribute('data-assignment-new')||b.dataset.unassign))||(!admin()&&b.hasAttribute('data-staff-new'))||(currentStaff.role==='团队'&&(b.dataset.pay||['order','client'].includes(b.dataset.new)||b.hasAttribute('data-product-new')||b.dataset.productEdit||b.hasAttribute('data-event-new')||b.dataset.eventEdit));if(forbidden){e.stopImmediatePropagation();e.preventDefault();toast('当前角色没有此操作权限');return}if(b.hasAttribute('data-assignment-new'))assignmentForm();if(b.dataset.unassign){access.assignments=access.assignments.filter(a=>a.id!==b.dataset.unassign);logDemo('取消资料分配');render()}if(b.hasAttribute('data-staff-new'))modal('添加员工 / 团队',`<form id="staff-form"><div class="modal-body"><div class="form-grid">${field('员工姓名','name','','text',true)}${field('登录 Email','email','','email',true)}<div class="field"><label for="staff-password">初始密码</label><input id="staff-password" name="password" type="password" autocomplete="new-password" minlength="12" disabled placeholder="Firebase 账号管理接通后填写"></div>${selectField('角色','role',['老板','Account','经理','团队'].map(r=>[r,r]))}</div><p>Firebase 自动开通账号尚未接通，因此密码栏暂时停用。现在只保存姓名、Email 和角色用于预览，不会创建可登录账号。</p></div>${controls}</form>`)},true);
permissionEventRoot.addEventListener('submit',e=>{const f=e.target;const forbidden=(!admin()&&f.id==='staff-form')||(!canAssign()&&f.id==='assignment-form')||(currentStaff.role==='团队'&&['pay-form','order-form','client-form','product-form','multi-event-form','event-form'].includes(f.id));if(forbidden){e.preventDefault();e.stopImmediatePropagation();return toast('当前角色没有此操作权限')}if(!['assignment-form','staff-form'].includes(f.id))return;e.preventDefault();e.stopImmediatePropagation();const d=Object.fromEntries(new FormData(f));if(f.id==='staff-form'){const email=(d.email||'').trim().toLowerCase();if(access.users.some(u=>(u.email||'').toLowerCase()===email))return toast('此 Email 已有员工记录');access.users.push({name:d.name,email,role:d.role,id:crypto.randomUUID()});}else{if(!access.users.some(u=>u.id===d.user&&u.role==='团队')||!['client','order'].includes(d.kind)||!(d.kind==='client'?fullDb.clients:fullDb.orders).some(r=>r.id===d.target))return toast('分配对象无效');if(access.assignments.some(a=>a.kind===d.kind&&a.target===d.target&&a.user===d.user))return toast('此资料已分配给该成员');access.assignments.push({...d,id:crypto.randomUUID(),by:currentStaff.name,time:new Date().toISOString()});}logDemo(f.id==='staff-form'?'新增预览员工':'分配客户 / 订单');render();$('#dialog').close();toast(f.id==='staff-form'?'已保存预览员工资料，尚未创建 Firebase 登录账号':'已保存')},true);
logDemo('进入角色预览');render();

