const permissionEventRoot=typeof window!=='undefined'?window:document;
// Local role preview only. Production authorization must be enforced by Firebase, not this UI.
const staffSeed=[{id:'boss',name:'老板',role:'老板'},{id:'account',name:'Account',role:'Account'},{id:'manager',name:'经理',role:'经理'},{id:'amanda',name:'Amanda',role:'团队'},{id:'jason',name:'Jason',role:'团队'}];
let access=typeof window!=='undefined'&&window.MACTION_INITIAL?structuredClone(window.MACTION_INITIAL.access):null;try{if(!access)access=JSON.parse(localStorage.getItem('maction-access-demo'))}catch{}access??={users:staffSeed,assignments:[],logs:[]};let currentStaff=typeof window!=='undefined'&&window.MACTION_INITIAL?window.MACTION_INITIAL.profile:access.users[0],fullDb=db;
const admin=()=>['老板','Account'].includes(currentStaff.role),canAssign=()=>admin()||(currentStaff.role==='经理'&&(typeof allowedRoleOption!=='function'||allowedRoleOption('assign'))),canData=()=>admin();
function roleActionBlocked(target,submit=false){if(admin())return false;if(submit?target.id==='pay-form':target.dataset?.pay)return true;if(typeof allowedRoleOption!=='function')return false;if(submit){return (!allowedRoleOption('editFollowups')&&['activity-form','note-form','outcome-form'].includes(target.id))||(!allowedRoleOption('editDelivery')&&['company-learner-form','learner-form','course-progress-form','service-progress-form','attendance-form','service-form'].includes(target.id))}const b=target,d=b.dataset;return (!allowedRoleOption('editFollowups')&&(d.new==='activity'||d.note||d.outcome||d.invite))||(!allowedRoleOption('editDelivery')&&(d.courseProgress||d.serviceProgress||d.learnerEdit||d.attendance||d.service||b.hasAttribute('data-add-company-learner')||b.hasAttribute('data-learner-new')))}
function storeAccess(){if(typeof window!=='undefined'&&window.MACTION_PRODUCTION)return;localStorage.setItem('maction-access-demo',JSON.stringify(access))}
function assignedClient(id){return access.assignments.some(a=>a.user===currentStaff.id&&a.kind==='client'&&a.target===id)}
function assignedOrder(o){return assignedClient(o.client)||access.assignments.some(a=>a.user===currentStaff.id&&a.kind==='order'&&a.target===o.id)}
function scopedData(){if(currentStaff.role!=='团队')return fullDb;const orders=fullDb.orders.filter(assignedOrder),ids=new Set(orders.map(o=>o.id)),clientIds=new Set(orders.map(o=>o.client));fullDb.clients.filter(c=>assignedClient(c.id)).forEach(c=>clientIds.add(c.id));const learners=fullDb.learners.filter(l=>ids.has(l.order)||(!l.order&&assignedClient(l.client))),learnerIds=new Set(learners.map(l=>l.id));return {...fullDb,clients:fullDb.clients.filter(c=>clientIds.has(c.id)),orders,payments:fullDb.payments.filter(p=>ids.has(p.order)),learners,learnerNotes:fullDb.learnerNotes.filter(n=>n.order?ids.has(n.order):learnerIds.has(n.learner)),services:fullDb.services.filter(s=>learnerIds.has(s.learner)),activities:fullDb.activities.filter(a=>assignedClient(a.client)||clientIds.has(a.client))}}
const priorSave=save;save=function(){if(currentStaff.role==='团队'){for(const k of ['activities','learnerNotes','services','learners'])for(const record of db[k])if(!fullDb[k].includes(record))fullDb[k].push(record);const scoped=db;db=fullDb;try{priorSave()}finally{db=scoped}}else{fullDb=db;priorSave()}storeAccess()};
names.permissions=['⚙','权限与分配'];names.loginLogs=['◷','登录记录'];navGroups.push(['系统管理',['permissions','loginLogs']]);
function logDemo(action,user=currentStaff){if(typeof window!=='undefined'&&window.MACTION_PRODUCTION)return;access.logs.push({id:crypto.randomUUID(),user:user.name,userId:user.id,role:user.role,time:new Date().toISOString(),action,mode:'角色模拟，非真实登录'});storeAccess()}
function staffSelect(){if(typeof window!=='undefined'&&window.MACTION_PRODUCTION)return '<strong>'+esc(currentStaff.name)+' · '+esc(currentStaff.role)+'</strong>';return `<label class="role-preview">角色预览<select id="staff-preview" aria-label="切换预览角色">${access.users.filter(u=>!u.inactive).map(u=>`<option value="${esc(u.id)}" ${u.id===currentStaff.id?'selected':''}>${esc(u.name)} · ${esc(u.role)}</option>`).join('')}</select></label>`}
function assignmentForm(){modal('分配客户 / 课程或服务订单',`<form id="assignment-form"><div class="modal-body"><div class="notice">分配整个客户：团队可查看该客户全部订单。分配单个订单：团队可查看客户开票资料和该订单的交付、付款与学员记录。</div><div class="form-grid">${selectField('分配范围','kind',[['order','单个课程 / 服务订单'],['client','整个客户']])}${selectField('团队成员','user',access.users.filter(u=>u.role==='团队'&&!u.inactive).map(u=>[u.id,u.name]))}${selectField('选择订单','target',fullDb.orders.map(o=>[o.id,client(o.client).name+' · '+product(o.product).name+' · '+o.id]))}</div></div>${controls}</form>`);$('#f-kind').onchange=()=>{$('#f-target').innerHTML=($('#f-kind').value==='client'?fullDb.clients.map(c=>[c.id,c.name+' · '+c.company]):fullDb.orders.map(o=>[o.id,client(o.client).name+' · '+product(o.product).name+' · '+o.id])).map(([id,label])=>`<option value="${esc(id)}">${esc(label)}</option>`).join('')};}
const beforePermissionsRender=render;render=function(){if(currentStaff.role==='团队')db=scopedData();if(!canData()&&view==='data')view='dashboard';if(!canAssign()&&['permissions','loginLogs'].includes(view))view='dashboard';if(['permissions','loginLogs'].includes(view)){const actual=view;view='clients';beforePermissionsRender();view=actual;$('#crumb').textContent=names[view][1];if(view==='permissions')$('#main').innerHTML=heading('权限与客户分配','经理分配客户或课程订单，团队仅查看自己的工作资料。',`<div class="actions">${admin()?'<button class="button" data-staff-new>＋ 添加员工</button>':''}<button class="button primary" data-assignment-new>＋ 分配资料</button></div>`)+`<div class="notice">目前为本机权限模拟。真实登录记录及服务器权限将在连接 Firebase 后生效。</div><section class="panel"><div class="panel-head"><h2>角色权限</h2></div>${table(['角色','资料范围','Import / Export','客户分配'],[['老板','全部资料','允许','允许'],['Account','全部资料','允许','允许'],['经理','全部客户与交付资料','禁止','允许'],['团队','仅分配客户 / 订单','禁止','禁止']].map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`))}</section><section class="panel" style="margin-top:24px"><div class="panel-head"><h2>当前分配记录</h2></div>${table(['团队成员','分配范围','客户 / 订单','分配人','操作'],access.assignments.map(a=>`<tr><td>${esc(access.users.find(u=>u.id===a.user)?.name)}</td><td>${a.kind==='client'?'整个客户':'单个订单'}</td><td>${esc(a.kind==='client'?fullDb.clients.find(c=>c.id===a.target)?.name:a.target)}</td><td>${esc(a.by)}</td><td><button class="link" data-unassign="${a.id}">取消分配</button></td></tr>`))}</section>`;else $('#main').innerHTML=heading('登录与操作记录','当前展示角色切换及权限操作的模拟记录。')+`<section class="panel">${table(['时间（马来西亚）','员工','角色','事件','记录类型'],[...access.logs].reverse().map(l=>`<tr><td>${esc(new Date(l.time).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur'}))}</td><td>${esc(l.user)}</td><td>${esc(l.role)}</td><td>${esc(l.action)}</td><td>${esc(l.mode)}</td></tr>`))}</section>`;}else beforePermissionsRender();const header=$('.header-right');header.innerHTML=staffSelect();document.querySelectorAll('#nav [data-view]').forEach(b=>{if((b.dataset.view==='data'&&!canData())||(['permissions','loginLogs'].includes(b.dataset.view)&&!canAssign()))b.hidden=true});if(!admin())document.querySelectorAll('[data-pay]').forEach(b=>b.hidden=true);if(!admin())document.querySelectorAll('[data-download],[data-import-csv],[data-import-json],#reset').forEach(b=>b.hidden=true);if(currentStaff.role==='团队')document.querySelectorAll('[data-new="order"],[data-new="client"],[data-pay],[data-product-new],[data-product-edit],[data-event-new],[data-event-edit]').forEach(b=>b.hidden=true)};
document.addEventListener('change',e=>{if(e.target.id==='staff-preview'){save();logDemo('结束角色预览');currentStaff=access.users.find(u=>u.id===e.target.value)||access.users[0];db=fullDb;logDemo('进入角色预览');view='dashboard';query='';filter='all';$('#dialog').close();render()}},true);
permissionEventRoot.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const forbidden=roleActionBlocked(b)||(!canData()&&(b.dataset.download||b.hasAttribute('data-import-csv')||b.hasAttribute('data-import-json')||b.hasAttribute('data-confirm-import')||b.id==='reset'))||(!canAssign()&&(b.hasAttribute('data-assignment-new')||b.dataset.unassign))||(!admin()&&b.hasAttribute('data-staff-new'))||(currentStaff.role==='团队'&&(b.dataset.pay||['order','client'].includes(b.dataset.new)||b.hasAttribute('data-product-new')||b.dataset.productEdit||b.hasAttribute('data-event-new')||b.dataset.eventEdit));if(forbidden){e.stopImmediatePropagation();e.preventDefault();toast('当前角色没有此操作权限');return}if(b.hasAttribute('data-assignment-new'))assignmentForm();if(b.dataset.unassign){access.assignments=access.assignments.filter(a=>a.id!==b.dataset.unassign);logDemo('取消资料分配');render()}if(b.hasAttribute('data-staff-new'))modal('添加员工 / 团队',`<form id="staff-form"><div class="modal-body"><div class="form-grid">${field('员工姓名','name','','text',true)}${field('登录 Email','email','','email',true)}<div class="field"><label for="staff-password">初始密码</label><input id="staff-password" name="password" type="password" autocomplete="new-password" minlength="12" ${typeof window!=='undefined'&&window.MACTION_PRODUCTION?'required':'disabled'} placeholder="至少12位密码"></div>${selectField('角色','role',['老板','Account','经理','团队'].map(r=>[r,r]))}</div><p>${typeof window!=='undefined'&&window.MACTION_PRODUCTION?'保存后会创建 Firebase 登录账号；密码只用于开通，不保存在客户资料或日志中。':'当前为账号管理预览。'}</p></div>${controls}</form>`)},true);
permissionEventRoot.addEventListener('submit',e=>{const f=e.target;const forbidden=roleActionBlocked(f,true)||(!admin()&&f.id==='staff-form')||(!canAssign()&&f.id==='assignment-form')||(currentStaff.role==='团队'&&['pay-form','order-form','client-form','product-form','multi-event-form','event-form'].includes(f.id));if(forbidden){e.preventDefault();e.stopImmediatePropagation();return toast('当前角色没有此操作权限')}if(!['assignment-form','staff-form'].includes(f.id))return;e.preventDefault();e.stopImmediatePropagation();const d=Object.fromEntries(new FormData(f));if(f.id==='staff-form'&&typeof window!=='undefined'&&window.MACTION_PRODUCTION){window.createCRMStaff(d);f.querySelector('[name=password]').value='';return}if(f.id==='staff-form'){const email=(d.email||'').trim().toLowerCase();if(access.users.some(u=>(u.email||'').toLowerCase()===email))return toast('此 Email 已有员工记录');access.users.push({name:d.name,email,role:d.role,id:crypto.randomUUID()});}else{if(!access.users.some(u=>u.id===d.user&&u.role==='团队')||!['client','order'].includes(d.kind)||!(d.kind==='client'?fullDb.clients:fullDb.orders).some(r=>r.id===d.target))return toast('分配对象无效');if(access.assignments.some(a=>a.kind===d.kind&&a.target===d.target&&a.user===d.user))return toast('此资料已分配给该成员');access.assignments.push({...d,id:crypto.randomUUID(),by:currentStaff.name,time:new Date().toISOString()});}logDemo(f.id==='staff-form'?'新增预览员工':'分配客户 / 订单');render();$('#dialog').close();toast(f.id==='staff-form'?'已保存预览员工资料，尚未创建 Firebase 登录账号':'已保存')},true);
logDemo('进入角色预览');render();


const beforePaymentPermissionForm=payForm;payForm=function(id){if(!admin())return toast('仅老板和 Account 可以更新收款记录');beforePaymentPermissionForm(id)};
const beforePaymentPermissionDetail=detail;detail=function(id){beforePaymentPermissionDetail(id);if(!admin())document.querySelectorAll('#dialog-content [data-pay]').forEach(b=>b.hidden=true)};

access.transferHistory??=[];
const ownerTransferSnapshot=new Map(fullDb.clients.map(c=>[c.id,c.owner]));
function transferableClients(source){const user=access.users.find(u=>u.name===source);const ids=new Set(access.assignments.filter(a=>a.user===user?.id).map(a=>a.kind==='client'?a.target:fullDb.orders.find(o=>o.id===a.target)?.client));return fullDb.clients.filter(c=>c.owner===source||ids.has(c.id))}
function transferClientOwners(ids,source,target,reason='',deactivate=false){
 if(!canAssign())throw Error('只有老板、Account 或获授权经理可以转交客户');
 const user=access.users.find(u=>u.name===source),recipient=target==='company'?null:access.users.find(u=>u.id===target&&u.role==='团队'&&!u.inactive),name=recipient?.name||'公司';
 if(target!=='company'&&!recipient)throw Error('新负责人无效');if(name===source)throw Error('请选择不同的新负责人');
 const eligible=new Set(transferableClients(source).map(c=>c.id));ids=[...new Set(ids)];if(!ids.length||ids.some(id=>!eligible.has(id)))throw Error('请选择有效的客户');
 if(deactivate&&(!user||currentStaff.id===user.id))throw Error('不能停用此员工');
 const orderIds=new Set(fullDb.orders.filter(o=>ids.includes(o.client)).map(o=>o.id));
 if(deactivate&&(transferableClients(source).some(c=>!ids.includes(c.id))||access.assignments.some(a=>a.user===user.id&&!(a.kind==='client'?ids.includes(a.target):orderIds.has(a.target)))))throw Error('请先转交该员工全部客户及订单，再停用员工');
 const timestamp=new Date().toISOString();
 for(const id of ids){const c=fullDb.clients.find(c=>c.id===id),orders=fullDb.orders.filter(o=>o.client===id),ownedServices=orders.filter(o=>productIsService(fullDb.products.find(p=>p.id===o.product))&&access.assignments.some(a=>a.kind==='order'&&a.target===o.id&&a.user===user?.id));
 const removed=access.assignments.filter(a=>a.user===user?.id&&(a.kind==='client'?a.target===id:orders.some(o=>o.id===a.target)));
 access.transferHistory.push({id:crypto.randomUUID(),client:id,clientName:c.name,from:c.owner||'未分配',source,to:name,time:timestamp,by:currentStaff.name,byId:currentStaff.id,reason,removedAssignments:structuredClone(removed)});
 access.assignments=access.assignments.filter(a=>!removed.includes(a));c.owner=name;ownerTransferSnapshot.set(id,name);
 if(recipient){for(const [kind,targetId] of [['client',id],...ownedServices.map(o=>['order',o.id])])if(!access.assignments.some(a=>a.user===recipient.id&&a.kind===kind&&a.target===targetId))access.assignments.push({id:crypto.randomUUID(),user:recipient.id,kind,target:targetId,by:currentStaff.name,time:timestamp})}
 fullDb.activities.filter(a=>a.client===id&&a.owner===source&&!a.done).forEach(a=>a.owner=name);
 }
 if(deactivate)user.inactive=true;db=fullDb;save();logDemo('批量转交 '+ids.length+' 位客户：'+source+' → '+name+(deactivate?'，停用原员工':''));return ids.length;
}
function transferHistoryHTML(id=''){return table(['时间','客户','原负责人','转出团队','新负责人','操作人','原因'],access.transferHistory.filter(h=>!id||h.client===id).slice().reverse().map(h=>'<tr>'+[new Date(h.time).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur'}),h.clientName,h.from,h.source,h.to,h.by,h.reason||'—'].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>'))}
function ownerTransferForm(){if(!canAssign())return toast('没有转交权限');const sources=[...new Set([...access.users.filter(u=>u.role==='团队'&&!u.inactive).map(u=>u.name),...fullDb.clients.map(c=>c.owner).filter(Boolean)])];modal('批量转交客户负责人','<form id="owner-transfer-form"><div class="modal-body"><div class="notice">转给公司将收回原团队的访问分配。转给团队将关联客户及原团队负责的服务。历史销售归属及付款记录不变。</div><div class="form-grid">'+selectField('原负责人','source',sources.map(x=>[x,x]))+selectField('转交给','target',[['company','公司（暂不分配团队）'],...access.users.filter(u=>u.role==='团队'&&!u.inactive).map(u=>[u.id,u.name])])+field('转交原因','reason','','text',true)+'</div><h3>勾选要转交的客户</h3><label><input type="checkbox" id="transfer-all"> 全选 / 取消全选</label><div id="transfer-clients" class="product-choices"></div>'+(admin()?"<label style=\"display:flex;gap:10px;margin-top:20px\"><input type=\"checkbox\" name=\"deactivate\" value=\"YES\"> 同时停用原员工（须转交全部客户；保留历史记录）</label>":'')+'</div>'+controls+'</form>');refreshTransferClients();}
function refreshTransferClients(){const source=$('#f-source').value;$('#transfer-clients').innerHTML=transferableClients(source).map(c=>'<label><input type="checkbox" name="transferClient" value="'+esc(c.id)+'"> '+esc(c.name)+' · '+esc(c.company)+'</label>').join('')||'<p>此负责人没有客户</p>';$('#transfer-all').checked=false}
const beforeTransferRender=render;render=function(){beforeTransferRender();if(!canAssign())return;if(['clients','permissions'].includes(view))$('#main .heading').insertAdjacentHTML('beforeend','<div class="actions"><button class="button" data-owner-transfer>批量转交负责人</button><button class="button" data-owner-history>负责人转交记录</button></div>')};
const beforeTransferDetail=detail;detail=function(id){beforeTransferDetail(id);if(canAssign())$('#dialog-content').insertAdjacentHTML('beforeend','<section class="modal-body"><h3>负责人转交记录</h3>'+transferHistoryHTML(id)+'</section>')};
permissionEventRoot.addEventListener('click',e=>{const b=e.target.closest('[data-owner-transfer],[data-owner-history]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(!canAssign())return toast('没有权限');if(b.hasAttribute('data-owner-transfer'))ownerTransferForm();else modal('负责人转交记录','<div class="modal-body">'+transferHistoryHTML()+'</div>')},true);
document.addEventListener('change',e=>{if(e.target.id==='f-source'&&$('#owner-transfer-form'))refreshTransferClients();if(e.target.id==='transfer-all')document.querySelectorAll('#transfer-clients input').forEach(x=>x.checked=e.target.checked)});
permissionEventRoot.addEventListener('submit',e=>{if(e.target.id!=='owner-transfer-form')return;e.preventDefault();e.stopImmediatePropagation();try{const values=[...new FormData(e.target)],d=Object.fromEntries(values),count=transferClientOwners(values.filter(([k])=>k==='transferClient').map(([,v])=>v),d.source,d.target,d.reason,d.deactivate==='YES');$('#dialog').close();render();toast('已转交 '+count+' 位客户，历史已保存')}catch(error){toast(error.message)}},true);

const beforeOwnerHistorySave=save;save=function(){for(const c of fullDb.clients){const old=ownerTransferSnapshot.get(c.id);if(old!==undefined&&old!==c.owner)access.transferHistory.push({id:crypto.randomUUID(),client:c.id,clientName:c.name,from:old||'未分配',source:old||'未分配',to:c.owner||'未分配',time:new Date().toISOString(),by:currentStaff.name,byId:currentStaff.id,reason:'客户资料编辑修改负责人'});ownerTransferSnapshot.set(c.id,c.owner)}beforeOwnerHistorySave()};
