// Adapter sends record deltas with optimistic version checks; server is the authority.
function initializeProductionAdapter(){
 let confirmed={db:structuredClone(fullDb),access:structuredClone(access)},saving=false,pending=false;
 const collections=['clients','products','orders','payments','activities','events','learners','learnerNotes','services'];
 const canonical=v=>{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v};
 const same=(a,b)=>JSON.stringify(canonical(a))===JSON.stringify(canonical(b));
 const clean=v=>JSON.parse(JSON.stringify(v));
 function patches(){const out=[];for(const key of [...collections,'assignments','transferHistory','users']){const source=collections.includes(key)?fullDb:access,old=collections.includes(key)?confirmed.db:confirmed.access;const prev=new Map((old[key]||[]).map(r=>[r.id,r])),next=new Map((source[key]||[]).map(r=>[r.id,r]));for(const id of new Set([...prev.keys(),...next.keys()])){const a=prev.get(id)||null,b=next.get(id)||null;if(!same(a,b))out.push({collection:key,id,before:a,after:b})}}for(const role of ['经理','团队']){const a=confirmed.access.roleOptions?.[role]||null,b=access.roleOptions?.[role]||null;if(!same(a,b))out.push({collection:'roleOptions',id:role,before:a,after:b})}return clean(out)}
 function install(state){window.MACTION_INITIAL=state;fullDb=state.db;access=state.access;currentStaff=state.profile;auditRecords=state.audit;db=currentStaff.role==='团队'?scopedData():fullDb;auditSnapshot=structuredClone(fullDb);accessSnapshot=structuredClone({assignments:access.assignments,users:access.users,roleSettings:[]});learnerSnapshot=structuredClone(fullDb.learners);ownerTransferSnapshot.clear();fullDb.clients.forEach(c=>ownerTransferSnapshot.set(c.id,c.owner));confirmed={db:structuredClone(fullDb),access:structuredClone(access)};}
 const existingToast=toast;toast=function(message){if(saving&&/已保存|已更新|已转交|已新增|已取消|已标记/.test(message))return;existingToast(message)};
 function overlay(on){let el=document.querySelector('#cloud-saving');if(on&&!el){el=document.createElement('div');el.id='cloud-saving';el.style='position:fixed;inset:0;z-index:2000;background:rgba(255,255,255,.8);display:grid;place-items:center;font-size:22px;font-weight:700';el.textContent='正在安全保存到云端…';document.body.append(el)}else if(!on)el?.remove()}
 async function sync(){if(saving){pending=true;return}const changes=patches();if(!changes.length)return;saving=true;overlay(true);try{await window.crmRequest({action:'mutate',patches:changes});const state=await window.crmRequest({action:'load'});install(state);render();existingToast('已保存到云端');}catch(error){try{install(await window.crmRequest({action:'load'}))}catch{fullDb=structuredClone(confirmed.db);access=structuredClone(confirmed.access);db=currentStaff.role==='团队'?scopedData():fullDb}render();existingToast(error.message||'保存失败，请刷新后重试')}finally{saving=false;overlay(false);if(pending){pending=false;await sync()}}}
 const finalSave=save;save=function(){for(const key of ['payments','activities'])for(const record of db[key])record.id??=crypto.randomUUID();finalSave();sync()};storeAccess=function(){if(!saving)queueMicrotask(sync)};
 window.createCRMStaff=async data=>{if(saving)return;saving=true;overlay(true);try{await window.crmRequest({action:'createStaff',...data});install(await window.crmRequest({action:'load'}));$('#dialog').close();render();existingToast('员工登录账号已开通')}catch(error){existingToast(error.message||'开通账号失败')}finally{saving=false;overlay(false)}};
 const productionRender=render;render=function(){productionRender();const sidebar=document.querySelector('.aside-bottom');if(sidebar)sidebar.innerHTML='<strong>MACTION CRM</strong><p>云端工作区</p>';const footer=document.querySelector('footer span');if(footer)footer.textContent='已连接 Firebase';document.querySelectorAll('.notice').forEach(n=>{if(/本机|本浏览器|角色模拟|权限模拟|预览日志/.test(n.textContent))n.textContent=n.textContent.includes('操作')?'操作日志由服务器记录，普通员工不可修改或删除。':'账号及访问权限由服务器验证。'});};
 permissionEventRoot.addEventListener('click',e=>{const b=e.target.closest('[data-preview-logout],#reset');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.id==='reset')return;window.crmLogout()},true);
 // Existing logout handler predates this listener; replace its entry point too.
 showLogin=function(){window.crmLogout()};
 window.addEventListener('beforeunload',e=>{if(saving){e.preventDefault();e.returnValue=''}});
 setInterval(async()=>{if(saving||document.querySelector('#dialog')?.open||document.hidden)return;try{install(await window.crmRequest({action:'load'}));render()}catch(error){if(['functions/permission-denied','functions/unauthenticated'].includes(error.code))window.crmLogout()}},60000);
 render();
}
