const roleCapabilities={viewClients:'查看客户管理',viewOrders:'查看订单及收款',viewCourses:'查看课程及学员',viewServices:'查看服务管理',editFollowups:'填写联系 / 学员跟进',editDelivery:'更新课程 / 服务进展',assign:'分配客户 / 服务'};
access.roleOptions??={};
function allowedRoleOption(key){if(admin())return true;const defaults={viewClients:true,viewOrders:true,viewCourses:true,viewServices:true,editFollowups:true,editDelivery:true,assign:currentStaff.role==='经理'};return (access.roleOptions?.[currentStaff.role]||{})[key]??defaults[key]}
function roleOptionsForm(){modal('角色权限 · 逐项设置',`<form id="role-options-form"><div class="modal-body"><div class="notice">老板和Account保留全部权限。经理仍禁止导入导出；经理和团队不能删除客户；团队始终只看分配资料。本设置当前为本机权限预览。</div>${['经理','团队'].map(role=>`<h3 style="margin-top:20px">${role}</h3><div class="product-choices">${Object.entries(roleCapabilities).filter(([k])=>role==='经理'||k!=='assign').map(([key,title])=>`<label><input type="checkbox" name="${role}:${key}" ${(access.roleOptions[role]?.[key]??true)?'checked':''}>${title}</label>`).join('')}</div>`).join('')}</div>${controls}</form>`)}
const canAssignBeforeOptions=canAssign;
// Keep established roles; allow managers to have assignment capability disabled.
const beforeRoleOptionsRender=render;render=function(){if(!admin()){const limits={clients:'viewClients',orders:'viewOrders',payments:'viewOrders',learners:'viewCourses',events:'viewCourses',serviceManagement:'viewServices'};if(limits[view]&&!allowedRoleOption(limits[view]))view='dashboard'}beforeRoleOptionsRender();if(view==='permissions'&&admin()){const b=document.createElement('button');b.className='button';b.textContent='逐项设置角色权限';b.dataset.roleOptions='1';$('#main .heading .actions').append(b)}if(!admin()){const viewMap={clients:'viewClients',orders:'viewOrders',payments:'viewOrders',learners:'viewCourses',events:'viewCourses',serviceManagement:'viewServices'};document.querySelectorAll('#nav [data-view]').forEach(b=>{const k=viewMap[b.dataset.view];if(k&&!allowedRoleOption(k))b.hidden=true});document.querySelectorAll('[data-assignment-new],[data-assign-service],[data-unassign]').forEach(b=>{if(!allowedRoleOption('assign'))b.hidden=true})}};
permissionEventRoot.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-role-options')){e.stopImmediatePropagation();if(admin())roleOptionsForm();return}const restricted=(!allowedRoleOption('assign')&&(b.hasAttribute('data-assignment-new')||b.dataset.assignService||b.dataset.unassign))||(!allowedRoleOption('editFollowups')&&(b.dataset.new==='activity'||b.dataset.note||b.dataset.outcome))||(!allowedRoleOption('editDelivery')&&(b.dataset.courseProgress||b.dataset.serviceProgress||b.dataset.learnerEdit||b.dataset.attendance));if(restricted){e.preventDefault();e.stopImmediatePropagation();toast('当前角色未获授权执行此操作')}},true);
permissionEventRoot.addEventListener('submit',e=>{if(e.target.id!=='role-options-form')return;e.preventDefault();e.stopImmediatePropagation();if(!admin())return toast('没有权限修改角色');const fd=new FormData(e.target);for(const role of ['经理','团队'])access.roleOptions[role]=Object.fromEntries(Object.keys(roleCapabilities).map(key=>[key,key==='assign'&&role==='团队'?false:fd.has(role+':'+key)]));logDemo('更新角色逐项权限');storeAccess();$('#dialog').close();render();toast('角色权限已更新')},true);
render();
